- name: "Create Folder {{ multi_folders }}"
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    url: http://172.31.4.34:8080
    user: admin
    password: "{{jenkins_password}}"
  loop: "{{ multi_folders }}"

- name: Create Pipeline Jobs
  ansible.builtin.include_tasks: mbranch-pipeline.yml
  loop: "{{ ci_pipeline_jobs }}"


