pipeline_jobs:
  - {name: "frontend", dir: "CIPipelines"}
  - {name: "cart", dir: "CIPipelines"}
  - {name: "catalogue", dir: "CIPipelines"}
  - {name: "user", dir: "CIPipelines"}
  - {name: "payment", dir: "CIPipelines"}
  - {name: "shipping", dir: "CIPipelines"}

folders:
  - CIPipelines
  - Folder2

ci_pipeline_jobs:
  - {name: "frontend", dir: "CIPipelines-MultiBranch"}
  - {name: "cart", dir: "CIPipelines-MultiBranch"}
  - {name: "catalogue", dir: "CIPipelines-MultiBranch"}
  - {name: "user", dir: "CIPipelines-MultiBranch"}
  - {name: "payment", dir: "CIPipelines-MultiBranch"}
  - {name: "shipping", dir: "CIPipelines-MultiBranch"}


multi_folders:
  - CIPipelines-MultiBranch