# Single Branch Pipeline
pipeline_jobs:
  - {name: "frontend", dir: "CIPipelines"}
  - {name: "cart", dir: "CIPipelines"}
  - {name: "catalogue", dir: "CIPipelines"}
  - {name: "user", dir: "CIPipelines"}
  - {name: "payment", dir: "CIPipelines"}
  - {name: "shipping", dir: "CIPipelines"}

folders:
  - CIPipelines
  - Folder2

# Multi Branch pipeline
ci_pipeline_jobs:
  - {name: "frontend", dir: "CIPipe-MBranch"}
  - {name: "cart", dir: "CIPipe-MBranch"}
  - {name: "catalogue", dir: "CIPipe-MBranch"}
  - {name: "user", dir: "CIPipe-MBranch"}
  - {name: "payment", dir: "CIPipe-MBranch"}
  - {name: "shipping", dir: "CIPipe-MBranch"}


multi_folders:
  - CIPipe-MBranch
  # Added for terraform
  - Infra

sbranch_pipeline_jobs:
  - {name: "09-roboshop-infra", dir: "Infra"}